# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    compose.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mguerga <mguerga@42lausanne.ch>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/12 11:15:41 by mguerga           #+#    #+#              #
#    Updated: 2024/06/17 11:36:13 by mguerga          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  nginx:
    container_name: nginx 
    depends_on:
      - wordpress
    networks: ["mynet"]
    build: requirements/nginx/
    volumes:
      - type: bind
        target: /etc/data
        source: /home/mguerga/data/WP
        bind:
          propagation: shared
          create_host_path: true
    env_file: ".env"
    ports:
      - "443:443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    networks: ["mynet"]
    depends_on:
      - mariadb 
    build: requirements/wordpress/ 
    volumes:
      - type: bind
        target: /etc/data
        source: /home/mguerga/data/WP
        bind:
          propagation: shared
          create_host_path: true
    env_file: ".env"
    restart: on-failure
  mariadb:
    container_name: mariadb 
    networks: ["mynet"]
    build: requirements/mariadb/
    volumes:
      - type: bind
        target: /var/lib/mysql 
        source: /home/mguerga/data/DB
        bind:
          propagation: shared
          create_host_path: true
    env_file: ".env"
    restart: on-failure

volumes:
  DB:
  WP:

networks:
  mynet:
