FROM alpine

WORKDIR /

COPY tools/maria.sh maria.sh 
COPY tools/maria2.sh maria2.sh 
COPY conf/my.cnf my.cnf 

VOLUME ["/home/mguerga/data/"]

RUN apk update && \
	apk add --no-cache mariadb mariadb-client && \
	mkdir /run/mysqld && \
	chown mysql:mysql /etc/my.cnf.d/ /run/mysqld /usr/share/mariadb/mysql_system_tables_data.sql

CMD ["sh", "maria.sh"]

EXPOSE 3306
