# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    compose.yaml                                       :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mguerga <mguerga@42lausanne.ch>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/03/12 11:15:41 by mguerga           #+#    #+#              #
#    Updated: 2024/06/13 13:24:12 by mguerga          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

services:
  nginx:
    container_name: nginx 
    depends_on:
      - wordpress
    networks: ["mynet"]
    build: nginx/
    volumes:
      - type: bind
        target: /etc/data
        source: /home/mguerga/data/WP
        bind:
          propagation: shared
          create_host_path: true
    ports:
      - "4430:443"
    restart: on-failure
  wordpress:
    container_name: wordpress
    networks: ["mynet"]
    depends_on:
      - mariadb 
    build: wordpress/ 
    volumes:
      - type: bind
        target: /etc/data
        source: /home/mguerga/data/WP
        bind:
          propagation: shared
          create_host_path: true
    ports:
      - "9000:9000"
    restart: on-failure
  mariadb:
    container_name: mariadb 
    networks: ["mynet"]
    build: mariadb/
    volumes:
      - type: bind
        target: /var/lib/mysql 
        source: /home/mguerga/data/DB
        bind:
          propagation: shared
          create_host_path: true
    environment:
      MARIADB_USER: wordp 
      MARIADB_DATABASE: 'db1' 
      MARIADB_PASSWORD: toor
      MARIADB_ROOT_PASSWORD: toor
    ports:
      - "3306:3306"
    restart: on-failure

volumes:
  DB:
  WP:

networks:
  mynet:
