FROM alpine:3.20.1

WORKDIR /
COPY tools/adminer.sh /adminer.sh

RUN apk update && \
	wget https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1-mysql.php -O adminer.php

CMD ["sh", "adminer.sh"]

