FROM alpine

WORKDIR /etc/data

COPY tools/wordpress1.sh wordpress1.sh 
COPY tools/wordpress2.sh /wordpress2.sh 
COPY conf/wp-config.php wp-config.php 

RUN apk update && \
	apk --no-cache add bash php83 php83-phar php83-fpm php83-mysqli

COPY conf/www.conf /etc/php83/php-fpm.d/www.conf

RUN	adduser -S nginx && \
	addgroup -S nginx && \
	ln -sf /dev/stdout /var/log/php83/error.log

RUN	sh wordpress1.sh

CMD ["sh", "/wordpress2.sh"]

EXPOSE 9000
