mariadb-secure-installation << EOF

n
n
Y
Y
Y
Y
EOF

mariadb << EOF
SELECT user,host FROM mysql.user;
CREATE DATABASE IF NOT EXISTS $WORDPRESS_DB_NAME;
CREATE USER IF NOT EXISTS '$WORDPRESS_DB_USER'@'172.28.%.%' IDENTIFIED BY '$WORDPRESS_DB_PASSWORD';
GRANT ALL PRIVILEGES ON $WORDPRESS_DB_NAME.* TO '$WORDPRESS_DB_USER'@'172.28.%.%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
SELECT user,host FROM mysql.user;
SHOW GRANTS FOR '$WORDPRESS_DB_USER'@'172.28.%.%';
SHOW DATABASES;
EOF
