FROM alpine:latest

WORKDIR /code
COPY nginx.conf . 
COPY 50x.html . 
COPY cert.pem . 
COPY fastcgi_params . 
COPY mime.types . 
COPY cert.key .


RUN apk update && \
	apk add nginx && \
	ln -sf /dev/stdout /var/log/nginx/error.log

EXPOSE 443 

CMD ["nginx", "-c", "/code/nginx.conf", "-g", "daemon off;"]

