FROM alpine:latest

COPY wordpress.sh wordpress.sh
COPY wp-config.php . 

RUN apk update && \
	apk --no-cache add php83 php83-phar php83-fpm php83-mysqli bash less mysql-client curl

COPY www.conf /etc/php83/php-fpm.d/www.conf

RUN	adduser -S nginx && \
	addgroup -S nginx && \
	php-fpm83 && \
	ln -sf /dev/stdout /var/log/php83/error.log


CMD ["sh", "wordpress.sh"]

EXPOSE 9000
