FROM alpine

WORKDIR /code
COPY /srcs/requirements/nginx/tools/favicon.ico /etc/data/wordpress/ 
COPY /srcs/requirements/nginx/tools/50x.html 50x.html 
COPY /secrets/cert.pem cert.pem
COPY /secrets/cert.key cert.key
COPY /srcs/requirements/nginx/conf/nginx.conf nginx.conf 
COPY /srcs/requirements/nginx/conf/fastcgi_params fastcgi_params 
COPY /srcs/requirements/nginx/conf/mime.types mime.types 


RUN apk update && \
	apk add --no-cache nginx && \
	ln -sf /dev/stdout /var/log/nginx/error.log

EXPOSE 443 

CMD ["nginx", "-c", "/code/nginx.conf", "-g", "daemon off;"]

