FROM alpine:latest

WORKDIR /

COPY maria.sh . 
COPY my.cnf . 

RUN apk update && \
	apk add --no-cache mariadb mariadb-client && \
	mkdir /run/mysqld && \
	chown mysql:mysql /etc/my.cnf.d/ /run/mysqld /usr/share/mariadb/mysql_system_tables_data.sql

CMD ["sh", "maria.sh"]

EXPOSE 3306
